### PR TITLE
fixed msg error when clientScope created with whitespace (#1997)

### LINKED ISSUE #1997: Creation of new scope with white space show error message
### Describe the bug

During the creation of new Client scope, error message is shown if name contains white spaces. Also it is possible to create a scope with white single white space and it makes impossible to access item details from the list

### Version

Keycloak 16.1.0 (WildFly Core 18.0.0.Final)

### Expected behavior

1. Should not show error message during the creation
2. Should not allow create scope with single whitespace

### Actual behavior

1. If scope with name 'one two' is created, error message appears _Could not create client scope: 'Error: Could not find the resource that you are looking for'_ but scope is created in the item list with this name: 'one_two'
2. Creates a client scope with empty name if single whitespace is placed in the name

### How to Reproduce?

1. Go to **Client Scopes** -> **Create Client Scope**
2. Try create new scope with name:
- 'one two' -> will show error message, and creates scope with name 'one_two'
- ' ' (single whitespace) -> will create scope with no name in the list

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ikhomyn**
## Motivation
Closes #1997 

## Brief Description
During creation of new client scope, if name contains white-space, error message is shown

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

**Comment by ikhomyn** [comment]
```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  authentication_policies.spec.ts          00:25        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  authentication_test.spec.ts              02:11       15       15        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  client_authorization_test.spec.ts        00:31        9        8        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_scopes_test.spec.ts               01:13       20       20        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_saml_test.spec.ts                00:30        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_test.spec.ts                     03:47       25       25        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  events_test.spec.ts                      01:45       14       14        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  group_test.spec.ts                       01:12        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_oidc_test.spec.t      00:50        5        5        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_saml_test.spec.t      01:57       12       12        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_test.spec.ts          01:17        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  login_test.spec.ts                       00:10        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  masthead_test.spec.ts                    00:28        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_export_test.spec.ts              00:25        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_import_test.spec.ts              00:58        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  realm_roles_test.spec.ts                 01:51        7        6        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_policies_test      01:06       18       18        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_profiles_test      00:59       21       21        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_events_test.spec.ts       02:43       17       16        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_tabs_test.spec.ts         00:49        6        6        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_user_profile_tab.spe      00:26        3        3        -        -        - │
  │    c.ts                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_test.spec.ts                       00:48        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_user_registration.spec.ts          00:17        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  sessions_test.spec.ts                    00:35        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_kerberos_test.spec.ts           01:10        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_hardcoded_mapper_test      01:58       12       12        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_mapper_test.spec.ts        02:01       12       12        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_test.spec.ts               01:17        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  users_test.spec.ts                       00:37       13       12        -        1        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  2 of 29 failed (7%)                      34:29      275      271        2        2        -  


```

File: src/client-scopes/details/ScopeForm.tsx [hunk 1]
```diff
@@ -55,6 +55,10 @@ export const ScopeForm = ({ clientScope, save }: ScopeFormProps) => {
       clientScope.attributes?.["display.on.consent.screen"] ?? "true",
   });
 
+  const validate = (event: any) => {
```
Comment (jonkoops) [inline src/client-scopes/details/ScopeForm.tsx:58]: Can you at the correct type here instead of `any`?

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Comment by ikhomyn** [comment]
@jonkoops I've set the type, should be okay

**Review by mfrances17 — APPROVED** [review]
LGTM, tested great. It's an ok from me to merge as long as all tests pass locally.

**Review by edewit — CHANGES_REQUESTED** [review]
So in order to not have whitepace we change the whitespace into `_` ? That is not what the old console does. I think it would be better to add a validate function to see if there are only spaces like this:

```jsx
<TextInput
        ref={register({
        required: true,
        validate: (value: string) =>
          !!value.trim() || t("common:required").toString(),
      })}
      type="text"
```

**Comment by ikhomyn** [comment]
> So in order to not have whitepace we change the whitespace into `_` ? That is not what the old console does. I think it would be better to add a validate function to see if there are only spaces like this:
> 
> ```js
> <TextInput
>         ref={register({
>         required: true,
>         validate: (value: string) =>
>           !!value.trim() || t("common:required").toString(),
>       })}
>       type="text"
> ```

Hi @edewit, I checked this and it works removing white-spaces around string but not in the middle.

The reason I replaced white space with _ is because when I create scope with name: 'a b' I am getting this:
Screenshot from 2022-03-01 09-45-21
And the item is created with forllowing name: 'a_b'
Screenshot from 2022-03-01 09-50-07

Should we keep that issue as it is in the old console only adding a white-space trim() to validate it?  Or can we also add replace ' ' with '_'  as well? Let me know how to better proceed. Thanks!

**Comment by edewit** [comment]
Yes I see, so it should be your fix and mine combined

**Comment by ikhomyn** [comment]
@edewit The thing is, when scope is created with same name as is created on server back side, then it redirects:
from (Client scope create)
Screenshot from 2022-03-01 14-24-02
to (Client scope details)
Screenshot from 2022-03-01 14-24-32
But if name is not the same, then seems like it is showing that err message and not redirecting to the page. Maybe there is a way to take the name value of the scope prior to redirection?

**Comment by edewit** [comment]
The error is here: https://github.com/edewit/keycloak-admin/blob/cf6413af41731b3b6ddbccd03f6bc90e911bcb79/src/client-scopes/form/ClientScopeForm.tsx#L123 it tries to find the created client scope by name. The name is already trimmed before creating it we could also put your regex here. That is much nicer then doing it on every key press

**Review by edewit — APPROVED** [review]

**Comment by ikhomyn** [comment]
@edewit Good catch. I didn't went so far, Thank you! I've tried the change manually and it works as expected. Do I need to rerun testsuite?

**Review by edewit — CHANGES_REQUESTED** [review]
we also need the validator right, to not allow a blank value?

**Comment by ikhomyn** [comment]
@edewit true, now it should be okay

**Review by edewit — APPROVED** [review]

**Comment by edewit** [comment]
:+1:

File: src/client-scopes/details/ScopeForm.tsx [hunk 2]
```diff
@@ -78,7 +78,11 @@ export const ScopeForm = ({ clientScope, save }: ScopeFormProps) => {
         helperTextInvalid={t("common:required")}
       >
         <TextInput
-          ref={register({ required: true })}
+          ref={register({
+            required: true,
+            validate: (value: string) =>
+              !!value.trim() || t("common:required").toString(),
```
Comment (jonkoops) [inline src/client-scopes/details/ScopeForm.tsx:84]: Why is `.toString()` needed here? Should the return value not always be a string?
```suggestion
              !!value.trim() || t("common:required"),
```

**Review by jonkoops — APPROVED** [review]
