### PR TITLE
Fix modal title in User Fed -> hardcoded-ldap-mapper

### LINKED ISSUE #1483: User Fed: hardcoded-ldap-role-mapper has buggy modal
1. Go to User Federation --> LDAP --> LDAP Mappers
2. Create new mapper
3. Choose `hardcoded-ldap-role-mapper` as mapper type

Role selection modal has wrong title.

Also in role selection modal, if I Filter by client and I select a client with no roles (such as account-console), the modal will collapse and I have no way to go back and select a different filter.  Instead it should show an empty state and allow me to choose something different.

### PR DESCRIPTION
**Pull request by jenny-s51**
## Motivation

Closes #1483 

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated

## Additional Notes

@ssilvert it looks like clients without assigned roles are no longer displayed as options in the filter dropdown, which seems to  address the filtering issue you raised - please confirm

### CODE REVIEW

**Comment by ssilvert** [comment]
@jenny-s51 I can confirm that the clients without assigned roles are no longer displayed.  So that must have been fixed somewhere else along the way.

I assume this is just fixing the title?

**Comment by jenny-s51** [comment]
@ssilvert yes that's correct!

**Review by ssilvert — APPROVED** [review]
LGTM

File: src/groups/GroupsSection.tsx [hunk 1]
```diff
@@ -121,8 +121,8 @@ export default function GroupsSection() {
                 <DropdownItem
                   data-testid="deleteGroup"
                   key="deleteGroup"
-                  onClick={async () => {
-                    await deleteGroup({ id });
+                  onClick={() => {
+                    deleteGroup({ id });
```
Comment (jonkoops) [inline src/groups/GroupsSection.tsx:125]: Why was this `await` removed? It is required for a bugfix, see https://github.com/keycloak/keycloak-admin-ui/pull/1634

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by mfrances17 — APPROVED** [review]
LGTM, works great - should be ok to merge once the async/await is back.

**Comment by jenny-s51** [comment]
Fixed @jonkoops @mfrances17 !

**Review by jonkoops — APPROVED** [review]
