### PR TITLE
Use correct field for authentication of e-mail server

### LINKED ISSUE #2701: SMTP configuration adds authentication instead of auth
### Describe the bug

Please see https://github.com/keycloak/keycloak/issues/12175 for more details. But the summary is that the email tab is using `authentication` to enable username/password login for sending emails. The real configuration parameter should be `auth` (note that you are doing something special to do the test, it was a mistake, it should be `auth`). I make it work doing this little change in `EmailTab.tsx`:

```diff
diff --git a/src/realm-settings/EmailTab.tsx b/src/realm-settings/EmailTab.tsx
index 9f0f855d..7e8fe9e5 100644
--- a/src/realm-settings/EmailTab.tsx
+++ b/src/realm-settings/EmailTab.tsx
@@ -56,7 +56,7 @@ export const RealmSettingsEmailTab = ({
 
   const authenticationEnabled = useWatch({
     control,
-    name: "smtpServer.authentication",
+    name: "smtpServer.auth",
     defaultValue: "",
   });
 
@@ -93,10 +93,8 @@ export const RealmSettingsEmailTab = ({
       serverSettings.starttls = serverSettings.starttls === true.toString();
     }
 
-    // For some reason the API wants a duplicate field for the authentication status.
-    // Somebody thought this was a good idea, so here we are.
-    if (serverSettings.authentication === true.toString()) {
-      serverSettings.auth = true;
+    if (typeof serverSettings.auth === "string") {
+      serverSettings.auth = serverSettings.auth === true.toString();
     }
 
     try {
@@ -321,7 +319,7 @@ export const RealmSettingsEmailTab = ({
               fieldId="kc-authentication"
             >
               <Controller
-                name="smtpServer.authentication"
+                name="smtpServer.auth"
                 control={control}
                 defaultValue=""
                 render={({ onChange, value }) => (
```

If you want I can send a PR or you can pick the little diff and integrate/inprove it.

Thanks!

### Version

18.0.0

### Expected behavior

Sending mails should work in normal processing out of the test.

### Actual behavior

Sending emails doesn't work as the server internally checks for [auth](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/email/DefaultEmailSenderProvider.java#L78).

### How to Reproduce?

See https://github.com/keycloak/keycloak/issues/12175.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jonkoops**
Closes #2701

### CODE REVIEW

File: src/realm-settings/EmailTab.tsx [hunk 1]
```diff
@@ -93,10 +93,8 @@ export const RealmSettingsEmailTab = ({
       serverSettings.starttls = serverSettings.starttls === true.toString();
     }
 
-    // For some reason the API wants a duplicate field for the authentication status.
-    // Somebody thought this was a good idea, so here we are.
-    if (serverSettings.authentication === true.toString()) {
-      serverSettings.auth = true;
+    if (serverSettings.auth === "string") {
+      serverSettings.auth = serverSettings.auth === true.toString();
```
Comment (edewit) [inline src/realm-settings/EmailTab.tsx:97]: This can be removed as well right? It's always a string but it can also be "false" so don't think we want to then put to change it to "true"

**Review by edewit — CHANGES_REQUESTED** [review]

File: src/realm-settings/EmailTab.tsx (hunk 1 above)
Comment (jonkoops) [reply src/realm-settings/EmailTab.tsx:97]: This is to work around a quirk in the Admin API. Basically when testing the connection the API expects these fields to be a `boolean`, but when saving the resource it expects that it's a `string` since the e-mail connection settings are saved as a `Map<string, string>`.

It's the way the Admin API works, unfortunately.

**Review by edewit — APPROVED** [review]
