### PR TITLE
Realm roles: fixes bug that prevents fields from being populated

### LINKED ISSUE #1838: Realm roles: role name is cleared when attributes are added
### Describe the bug

There are a few bugs in the realm roles section:

- When a new realm role is created, it takes you to the "Details" tab -- the name and description in this form do not get populated with the data for the new realm role.
- When an attribute is added to the a realm role, the `name` attribute is set to `""` at `save`. If you navigate back to the roles list, the link is no longer clickable because the realm name has been replaced with an empty string.

### Version

16.1

### Expected behavior

Details tab should be populated with the field values from the server, role name should not be cleared on attributes save

### How to Reproduce?

See above

### Anything else?

Was working on updates to the `AttributesInput` component in another issue, and discovered these bugs. Investigating.

### PR DESCRIPTION
**Pull request by jenny-s51**
Closes #1838 

Finishing up a PR that will add selectable functionality to [AttributeInput](https://github.com/keycloak/keycloak-admin-ui/blob/0bbd4ddad1b0fe3eeac9942b88539933f2e66c3a/src/components/attribute-input/AttributeInput.tsx) -- however while testing, I discovered the data could not be saved correctly due to this bug.

After a bunch of investigating, this seems like it's a timing issue.

### CODE REVIEW

File: src/realm-roles/RealmRoleTabs.tsx [hunk 1]
```diff
@@ -93,14 +93,20 @@ export default function RealmRoleTabs() {
...
-        Object.entries(convertedRole).map((entry) => {
-          setValue(entry[0], entry[1]);
-        });
+        setTimeout(() => {
+          Object.entries(convertedRole).map((entry) => {
+            setValue(entry[0], entry[1]);
+          });
+        }, 5);
+
+        if (url.includes("/attributes")) {
```
Comment (edewit) [inline src/realm-roles/RealmRoleTabs.tsx:102]: This seem like a workaround also the timout of 5 milliseconds I don't see why that would be needed

**Review by edewit — CHANGES_REQUESTED** [review]

File: src/realm-roles/RealmRoleTabs.tsx (hunk 1 above)
Comment (jenny-s51) [reply src/realm-roles/RealmRoleTabs.tsx]: Ah you're right, reordered the hook and the conditional and this seemed to resolve it.

**Review by jonkoops — APPROVED** [review]

**Review by edewit — APPROVED** [review]
