### PR TITLE
Changed button text from Delete to Revoke (Issue 1703)

### LINKED ISSUE #1703: [UX Review] Optimize the button wording of the revoke modal in User consents
### Describe the bug

In the User-Consents page, there will be a modal popup after clicking the **Revoke** option inside the kebab menu. In this modal, the primary button is "Delete". We can change the button from "Delete" to "Revoke" as shown in the screenshot below. Thanks.
Screen Shot 2021-12-14 at 2 01 11 PM

### Version

New admin UI

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dominikkawka**
## Motivation
Close #1703

## Brief Description
See #1703

## Verification Steps
1. You can enable the "Consent required" and "Display client on screen" in the settings page of the "security-admin-console-v2" client.
2. Then you can logout and login again.
3. You will find some consents in the User>Consent page.
4. After clicking the kebab menu, there will be an option list that includes "Revoke" option.

image

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

File: src/user/UserConsents.tsx [hunk 1]
```diff
@@ -65,7 +65,7 @@ export const UserConsents = () => {
     messageKey: t("users:revokeClientScopes", {
       clientId: selectedClient?.clientId,
     }),
-    continueButtonLabel: "common:delete",
+    continueButtonLabel: "common:Revoke",
```
Comment (jonkoops) [inline src/user/UserConsents.tsx:68]: I believe this should start with a lower case.
```suggestion
    continueButtonLabel: "common:revoke",
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: src/user/UserConsents.tsx (hunk 1 above)
Comment (dominikkawka) [reply src/user/UserConsents.tsx:68]: When I change it to lower case it appears as lower case in the button. revoke doesn't seem to be effected by "common"
I looked around for a few min to see if I could but wasn't able to do so. 

image

Comment (jonkoops) [reply src/user/UserConsents.tsx:68]: I think this is because this key does not exist in any of the language bundles, so instead it defaults to the name of the key. You'll have to add a `revoke` entry to [`public/resources/en/common.json`](https://github.com/keycloak/keycloak-admin-ui/blob/main/public/resources/en/common.json).

**Review by jonkoops — APPROVED** [review]
