### PR TITLE
Consents UI fixes

### LINKED ISSUE #668: [UX Review] User - Consents
Hi @jenny-s51, I've reviewed the "Consents" tab, there are some finetuning. Please check them.

> Screen Shot 2021-06-04 at 3 07 56 PM

1. We can remove this redundant line.
2. There is no distance between the tab bar and the border.
3. We can add a search bar here in order to help users search for some info.
4. If there are too many “Granted client scopes" here to show, we can add a label to show the number of the hidden client scopes, as shown in the picture below. 

> Screen Shot 2021-06-04 at 3 38 58 PM

5. Each row should have a kebab icon. Click the kebab icon can revoke the consent.

> Screen Shot 2021-06-04 at 3 39 34 PM

6. There is no distance between the table and the border.

### PR DESCRIPTION
**Pull request by jenny-s51**
## Motivation

Closes #668 

## Verification Steps

1. Go to client scopes -> create a new client scope.
2. Set the “Type” to “default” and make sure “Display on consent screen” is enabled.
3. Repeat for however many client scopes you want to create/grant.
4. Go to Clients and make sure both security-admin-console and security-admin-console-v2 have “Consent required” set to “on” under Login Settings
5. Go to Clients -> Client Scopes and then add the new client scopes as “Default”
6. Log out of both the new admin console and the old one
7. Log back into both
8. It should ask you to verify the new consents -> click accept/yes
9. Go to Users -> admin -> consents and you should see them listed there

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

### CODE REVIEW

**Review by mfrances17 — CHANGES_REQUESTED** [review]
Everything looks like it was addressed, well done. Thanks for adding the expanded verification steps, it helped a lot. One small change to handle the string better than using the concatenation.

File: src/user/UserConsents.tsx [hunk 1]
```diff
@@ -43,52 +70,83 @@ export const UserConsents = () => {
     return <>{moment(lastUpdatedDate).format("MM/DD/YY hh:MM A")}</>;
   };
 
+  const [toggleDeleteDialog, DeleteConfirm] = useConfirmDialog({
+    titleKey: "users:revokeClientScopesTitle",
+    messageKey: t("users:revokeClientScopes") + selectedClient?.clientId + "?",
```
Comment (mfrances17) [inline src/user/UserConsents.tsx:75]: Recommend doing something like this instead of concatenating the string here:
```
    messageKey: t("users:revokeClientScopes", {
      clientId: selectedClient?.clientId,
    }),
```

File: src/user/messages.json [hunk 2]
```diff
@@ -60,6 +60,11 @@
     "noConsents": "No consents",
     "noConsentsText": "The consents will only be recorded when users try to access a client that is configured to require consent. In that case, users will get a consent page which asks them to grant access to the client.",
     "whoWillAppearLinkText": "Who will appear in this group list?",
-    "whoWillAppearPopoverText": "Groups are hierarchical. When you select Direct Membership, you see only the child group that the user joined. Ancestor groups are not included."
+    "whoWillAppearPopoverText": "Groups are hierarchical. When you select Direct Membership, you see only the child group that the user joined. Ancestor groups are not included.",
+    "revoke": "Revoke",
+    "revokeClientScopesTitle": "Revoke all granted client scopes?",
+    "revokeClientScopes": "Are you sure you want to revoke all granted client scopes for ",
```
Comment (mfrances17) [inline src/user/messages.json:66]: And change the message to:
```
    "revokeClientScopes": "Are you sure you want to revoke all granted client scopes for {{clientId}}?",
```

File: src/user/UserConsents.tsx (hunk 1 above)
Comment (ssilvert) [reply src/user/UserConsents.tsx:75]: > Recommend doing something like this instead of concatenating the string here:
> 
> ```
>     messageKey: t("users:revokeClientScopes", {
>       clientId: selectedClient?.clientId,
>     }),
> ```

Good catch @mfrances17.  This is actually not just a recommendation.  It's a must-do.  In different languages, the placement of the param within the sentence can be different, which means that you can't translate it correctly if that placement is hard-coded.  So concatenation of localized strings should almost always be avoided.

Also concur with @mfrances17 overall.  I tried it out and it looks really good.

Comment (jenny-s51) [reply src/user/UserConsents.tsx]: @ssilvert That makes sense, thank you for your helpful clarification on this

**Comment by jenny-s51** [comment]
@mfrances17 @ssilvert Thank you for your helpful feedback and reviews! I've addressed the localization instance per your review comments
