### PR TITLE
fixed Consent screen text was not shown

### LINKED ISSUE #2051: Clients scopes Consent screen text value is not saved
### Describe the bug

Unable to modify/set Consent screen text value of Client scopes, getting empty value.

### Version

Keycloak 16.1.0 (WildFly Core 18.0.0.Final)

### Expected behavior

Perform edit and save operation of Consent screen text value

### Actual behavior

Unable to set/edit Consent screen text value

### How to Reproduce?

1. Go to **Client Scopes**
2. Go to **Client scope details** of any item
3. Set/edit **Consent screen text** value and save.
4. Navigate again to **Client Scopes** and go to scope details of the same item.
5. Observe that value is empty in **Consent screen text**

If **Consent screen text** input is not shown by default, it is affected by #1991

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ikhomyn**
## Motivation
Closes #2051 & #1991 

## Brief Description
Fixed **Consent screen text** input was not shown when switch **Display on consent screen** was turned ON. Also fixed issue when **Consent screen text** was impossible to set/modify.
Screenshot from 2022-02-24 15-13-38

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

**Comment by ikhomyn** [comment]
```
 (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  authentication_policies.spec.ts          00:28        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  authentication_test.spec.ts              02:11       15       15        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_authorization_test.spec.ts        00:32        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_scopes_test.spec.ts               01:15       20       20        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_saml_test.spec.ts                00:30        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_test.spec.ts                     03:49       25       25        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  events_test.spec.ts                      01:46       14       14        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  group_test.spec.ts                       01:15        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_oidc_test.spec.t      00:51        5        5        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_saml_test.spec.t      01:56       12       12        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_test.spec.ts          01:17        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  login_test.spec.ts                       00:10        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  masthead_test.spec.ts                    00:28        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_export_test.spec.ts              00:25        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_import_test.spec.ts              00:59        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_roles_test.spec.ts                 00:22        7        7        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_policies_test      01:01       18       18        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_profiles_test      00:59       21       21        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_events_test.spec.ts       02:43       17       16        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_tabs_test.spec.ts         00:49        6        6        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_user_profile_tab.spe      00:26        3        3        -        -        - │
  │    c.ts                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_test.spec.ts                       00:48        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_user_registration.spec.ts          00:16        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  sessions_test.spec.ts                    00:35        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_kerberos_test.spec.ts           01:12        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_hardcoded_mapper_test      02:00       12       12        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_mapper_test.spec.ts        02:00       12       12        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_test.spec.ts               01:18        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  users_test.spec.ts                       00:37       13       12        -        1        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        33:10      275      273        -        2        -  

```

**Comment by ikhomyn** [comment]
Only I have a doubt if **Display on consent screen** should be turned ON by default as it was before I the changes? Or better to have it disabled by default?

File: src/client-scopes/details/ScopeForm.tsx [hunk 1]
```diff
@@ -49,9 +49,15 @@ export const ScopeForm = ({ clientScope, save }: ScopeFormProps) => {
   const [openType, setOpenType] = useState(false);
   const { id } = useParams<{ id: string }>();
 
+  const displayOnConsentScreenEnabled =
+    clientScope["attributes"]?.["display.on.consent.screen"];
```
Comment (jonkoops) [inline src/client-scopes/details/ScopeForm.tsx:53]: You don't have to use the bracket notation here for the `attributes` property.

```suggestion
    clientScope.attributes?.["display.on.consent.screen"];
```

File: src/client-scopes/details/ScopeForm.tsx [hunk 2]
```diff
@@ -49,9 +49,15 @@ export const ScopeForm = ({ clientScope, save }: ScopeFormProps) => {
...
   const displayOnConsentScreen = useWatch({
     control,
     name: "attributes.display.on.consent.screen",
+    defaultValue:
+      displayOnConsentScreenEnabled == undefined
+        ? "true"
+        : displayOnConsentScreenEnabled,
```
Comment (jonkoops) [inline src/client-scopes/details/ScopeForm.tsx:60]: I think you can shorten your code here by getting rid of the intermediate variable. If you cast the attribute here directly to a boolean and then back to a string it will automatically turn undefined values into `false`.

```suggestion
    defaultValue: Boolean(clientScope.attributes?.["display.on.consent.screen"]).toString(),
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: src/client-scopes/details/ScopeForm.tsx (hunk 2 above)
Comment (ikhomyn) [reply src/client-scopes/details/ScopeForm.tsx:60]: @jonkoops Sure, looks better. Thanks!

**Review by ikhomyn — COMMENTED** [review]
Hmm, I just tried it, and during the creation of new scope, when value consent is undefined, it converts to false, but for existent scope, whether value is "true" or "false" it cast to Boolean True always as there is a string.

File: src/client-scopes/details/ScopeForm.tsx [hunk 3]
```diff
@@ -52,6 +52,10 @@ export const ScopeForm = ({ clientScope, save }: ScopeFormProps) => {
   const displayOnConsentScreen = useWatch({
     control,
     name: "attributes.display.on.consent.screen",
+    defaultValue:
+      clientScope.attributes?.["display.on.consent.screen"] === undefined
+        ? "true"
+        : clientScope.attributes["display.on.consent.screen"],
```
Comment (jonkoops) [inline src/client-scopes/details/ScopeForm.tsx:58]: Perhaps we can use [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) here to fall back to `"true"`?
```suggestion
    defaultValue: clientScope.attributes?.["display.on.consent.screen"] ?? "true",
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: src/client-scopes/details/ScopeForm.tsx (hunk 3 above)
Comment (ikhomyn) [reply src/client-scopes/details/ScopeForm.tsx:58]: Tried this one and works same way, thank you!

Comment (jonkoops) [reply src/client-scopes/details/ScopeForm.tsx]: Awesome!

**Comment by jonkoops** [comment]
@ikhomyn If you can fix the linting error we can go ahead and merge this.

**Comment by ikhomyn** [comment]
@jonkoops now should be fine. thanks!

**Review by jonkoops — APPROVED** [review]
