### PR TITLE
modal fixes for predefined mappers

### LINKED ISSUE #1682: [UX Review] Some fine-tuning of adding predefined mappers
### Describe the bug

There is some fine-tuning for the "Add predefined mappers" modal as shown in the screenshot below. Please check and fix them at your convenience. Thanks.

Screen Shot 2021-12-09 at 4 03 44 PM

1. Change the title from "Choose a mapper type" to "Add predefined mappers”.     
2. In the modal, there should be a checkbox to select all mappers.

Notes: This modal is used by the "Clients> Mappers" tab and "Client scopes> Client scopes details> Mappers" tab, so we can fix these issues across all of these pages that used this modal.

### Version

New UI

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jenny-s51**
## Motivation

Closes #1682

### CODE REVIEW

File: src/client-scopes/add/MapperDialog.tsx [hunk 1]
```diff
@@ -179,12 +179,21 @@ export const AddMapperDialog = (props: AddMapperDialogProps) => {
...
           cells={header}
           onSelect={(_, isSelected, rowIndex) => {
-            rows[rowIndex].selected = isSelected;
-            setRows([...rows]);
+            if (rowIndex === -1) {
+              setRows(
+                rows.map((oneRow) => {
+                  oneRow.selected = isSelected;
+                  return oneRow;
+                })
```
Comment (jonkoops) [inline src/client-scopes/add/MapperDialog.tsx:187]: Not sure if you are mutating the original object to keep reference equality, but if not you could also do:
```suggestion
                rows.map((row) => ({
                  ...row,
                  selected: isSelected,
                }))
```

**Review by jonkoops — APPROVED** [review]
