### PR TITLE
External link fixes for a11y and spacing

### LINKED ISSUE #98: External link icon spacing
The external link icon does not have the correct spacing. I think we may want to use the Button link component to ensure proper spacing.

### PR DESCRIPTION
**Pull request by srambach**
Changes the external link component to use the PatternFly Button component (link variant) which will increase a11y and ensure proper spacing.

Fixes #98

### CODE REVIEW

File: src/components/external-link/ExternalLink.tsx [hunk 1]
```diff
@@ -1,15 +1,22 @@
 import React from "react";
 import { ExternalLinkAltIcon } from "@patternfly/react-icons";
+import { Button } from "@patternfly/react-core";
 
 export const ExternalLink = ({
   title,
   href,
   ...rest
 }: React.HTMLProps<HTMLAnchorElement>) => {
```
Comment (edewit) [inline src/components/external-link/ExternalLink.tsx:9]: You'll have to change this to:
```suggestion
}: ButtonProps) => {
```

**Review by edewit — APPROVED** [review]

**Review by edewit — APPROVED** [review]
cool you found it, sorry but I didn't have time yesterday

**Review by jenny-s51 — APPROVED** [review]
Hooray, CI tests are passing! LGTM 🚀
