### PR TITLE
Identity Providers(mappers): fix help text

### LINKED ISSUE #1205: Identity Providers(mappers): Fix help text for name and Mapper Type
Help text is incorrect for Name and Mapper type.  Note that in the old console, the help text for Mapper type changes based on which one you select.

_Originally posted by @ssilvert in https://github.com/keycloak/keycloak-admin-ui/pull/1140#pullrequestreview-761333486_

### PR DESCRIPTION
**Pull request by jenny-s51**
## Motivation

Closes #1205 

## Verification Steps

1. Go to Identity Providers -> Select a Provider -> Click Mappers tab
2. Add a mapper
3. Verify that the help text for the "Name" field is correct.
4. Verify that the help text for all mapper types changes with the selected mapper type. 

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated

### CODE REVIEW

File: src/identity-providers/help.ts [hunk 1]
```diff
@@ -107,8 +107,19 @@ export default {
     addIdpMapperName: "Name of the mapper.",
     syncModeOverride:
       "Overrides the default sync mode of the IDP for this mapper. Values are: 'legacy' to keep the behaviour before this option was introduced, 'import' to only import the user once during first login of the user with this identity provider, 'force' to always update the user during every login with this identity provider and 'inherit' to use the sync mode defined in the identity provider for this mapper.",
-    mapperType:
+    advancedAttributeToRole:
       "If the set of attributes exists and can be matched, grant the user the specified realm or client role.",
+    usernameTemplateImporter: "Format the username to import",
```
Comment (mfrances17) [inline src/identity-providers/help.ts:112]: small nit but you should add a period at the end here, it especially stands out because the others are all punctuated

**Review by mfrances17 — CHANGES_REQUESTED** [review]
i'm getting ``name` prop should be in object shape: name="test[index].name"` whenever i the mapper type dropdown opens and closes, which fills up the console window pretty quickly. we should investigate to see why that is happening.

**Comment by jenny-s51** [comment]
@mfrances17 nice catch - thank you! addressed your comment and got rid of that console warning

File: src/identity-providers/help.ts (hunk 1 above)
Comment (mfrances17) [reply src/identity-providers/help.ts]: these are both fixed in the latest push, nice job. LGTM!

**Review by mfrances17 — APPROVED** [review]
